### ISSUE TITLE
`\Parable\Console\Parameter` can't handle `--option=value` 

### ISSUE THREAD

**Issue by devvoh** [devvoh/parable#15]
It will handle `--option value` just fine, but the equals-sign makes it not recognise the option.

Maek fix do work proper.

**Comment by jerry1970** [comment]
Is `--option=value` a proper syntax? I've never seen it.

**Comment by devvoh** [comment]
It is. The ecosystem standard is Symfony Console, whether I like it or not. Composer uses it, and that's a major part of the current ecosystem (as you well know).

So check out the following: https://symfony.com/doc/current/components/console/console_arguments.html

I don't currently offer arguments at all, figuring values-optional option parameters offer all the functionality I personally need.

I've considered adding arguments, but I'm not sure. Any input from different viewpoints would be appreciated.

**Comment by jerry1970** [comment]
If `--option=value` is a common way to pass arguments to the script, it would indeed be very nice to see this format accepted, so agree with your inital post to fix that.

Regarding arguments, I have several command line scripts that accept arguments, so I would be in favour of including those as well. Low priority, though.

**Comment by devvoh** [comment]
Should be fixed in 0.12.5. Reopen if it requires fixes!
