### ISSUE TITLE
Json->prepare() should have check on valid json_encode

### ISSUE THREAD

**Issue by jerry1970** [devvoh/parable#18]
It took a while to find out why a controller action returned `false` but it was something in an array that could not be converted to a json. The line `$content = json_encode($content)` made `$content = false`. 

`json_last_error_msg()` says "Malformed UTF-8 characters, possibly incorrectly encoded". Something with encoding but I am sure my database table is in UTF8 and all scripts are too. Will look into this.

**Comment by devvoh** [comment]
Hmm, please do let me know what caused this. In the meantime, I think I'll throw an Exception in cases like these. Good find regardless!

**Comment by devvoh** [comment]
Fixed in release 0.12.7 :)
