### ISSUE TITLE
Http\Url::getUrl('/') gives domain plus index.php

### ISSUE THREAD

**Issue by jerry1970** [devvoh/parable#22]
When calling this in a view template:
```
<?= $this->url->getUrl('/') ?>
```
the result is `http://project.dev/index.php/`.
I expected just `http://project.dev/`.

I'm on version 0.12.7.

**Comment by devvoh** [comment]
Can you share your main Config with the parable data? So obviously I'm not looking for your db credentials ;)

This has to do with your homeDir setup, and I'll fix this ASAP and add some tests to precent this in the future.

**Comment by jerry1970** [comment]
Oh wait, that might be a leftover from a previous version, I have not set `homeDir` in the config. My `public_html` (as assumed by the Apache config that I cannot change) is still a symlink to Parable's `public`.

What is the correct syntax?

**Comment by devvoh** [comment]
Check https://github.com/devvoh/parable/blob/master/structure/app/Config/App.php_struct for the default Config. Let me know if that works!

**Comment by jerry1970** [comment]
Config is now:
```
        $config['parable'] = [
            'app' => [
                'title' => 'Test Project',
                'homeDir' => 'public_html',
            ],
```
But this in a template file:
```
<br /><?= $this->url->getUrl('/') ?>
```
gives me this:
```
http://testproject.dev/index.php/ 
```

Any idea?

**Comment by devvoh** [comment]
What's the return value of `$this->url->getBasePath()`?

**Comment by jerry1970** [comment]
`/public_html/index.php`

**Comment by devvoh** [comment]
That's what it should be. Okay. Can you tell me what the return values are for the following 2?

`$this->request->getScriptName()`
`$this->url->getBaseUrl()`

**Comment by jerry1970** [comment]
Sure:
```
/index.php
http://testproject.dev/index.php 
```

**Comment by devvoh** [comment]
That's exactly what I needed to know. 0.12.8 is building in develop as we speak.

So of course you, the weird one, place Parable outside of the document root. So the document root isn't actually part of the script name. So it can't find the homeDir value + index.php, so it doesn't strip it, leaving index.php.

Good bug find :P

**Comment by devvoh** [comment]
https://github.com/devvoh/parable/releases/tag/0.12.8

There ya go! Just `composer update` that mofo and you should be fine!

Let me know if it works :)

**Comment by jerry1970** [comment]
PHPStorm, right-click on composer.json, Composer > Update...
```
http://testproject.dev/
```
:+1: :smiley:

**Comment by jerry1970** [comment]
I forgot I was using it differently from what you intended (framework outside doc root)... ;)

**Comment by devvoh** [comment]
It's cool, this was a good find and a necessary bugfix. To support different home dirs, it's necessary to make sure everything else works with it too.

:smiley:
