### ISSUE TITLE
This project needs a cool icon...

### ISSUE THREAD

**Issue by jerry1970** [devvoh/parable#24]
...so I can add it to the About page of my site.
:smiley:

**Comment by devvoh** [comment]
_And thus started the only issue he could never resolve..._

**Comment by devvoh** [comment]
(Though that doesn't mean I'm not going to try! I've managed to convince someone who's _good_ at this stuff to take a stab at it!)

**Comment by devvoh** [comment]
Closing this issue for now. It's not forgotten though.
