### ISSUE TITLE
Code style consistency before V1 release

### ISSUE THREAD

**Issue by FaaPz** [devvoh/parable#26]
You could use [Style CI](https://styleci.io/). It's free for open source! 🙌 
Or use [PHP Coding Standards Fixer](http://cs.sensiolabs.org/), manually... (no SaaS, very sad!)

**Comment by devvoh** [comment]
Funny, StyleCI returns 4 issues, and all of them seem to be whitespace issues :p

Maybe it's not as necessary as you think? I used the psr2 preset. If there's any specific code style inconsistencies you think should be addressed, could you point some out?

**Comment by devvoh** [comment]
StyleCI has been added regardless. Also the badge.

In 0.12.13 (https://github.com/devvoh/parable/releases/tag/0.12.13), all StyleCI issues with PSR-2 preset have been fixed 😁
