### ISSUE TITLE
More love for Parable Console, create your own commands

### ISSUE THREAD

**Issue by FaaPz** [devvoh/parable#3]
**Example command class:**
```php
class ModelMakeCommand extends \Parable\Console\Command
{
    protected $name = 'make:model';

    protected $description = 'Create a new model class';

    public function fire()
    {
        parent::fire();

        // ...
    }
}
```

- Move `parable` executable one level up (please? 😇 ).
- Add new `\Commands` namespace.
- Export `app/Commands` with `InitializeParableCommand`.
- Things I've missed...

**Some inspiration (copied from Laravel Console):**
```php
/** Run the console command. */
public function run(\Parable\Console\Input $input, \Parable\Console\Output $output)

/** Execute the console command. */
public function execute(\Parable\Console\Input $input, \Parable\Console\Output $output)

/** Call another console command. */
public function call($command, array $args = [])

/** Call another console command silently. */
public function callSilent($command, array $args = [])
```

**Comment by devvoh** [comment]
I'm not likely to follow your examples literally, but I do like the idea. I'm planning on making this the focus for 0.9.3. Thanks for opening this issue :)

**Comment by devvoh** [comment]
See 8ee376d for some initial changes towards this end.

**Comment by devvoh** [comment]
So this got a little out of hand. It's part of 0.10.0 and I think that with c196abc the essence of this issue has been fulfilled. You can either re-open this issue or make a more specific one if there's anything essential missing, but otherwise I'll consider this one solved :smile:
