### ISSUE TITLE
Add all 'parable.*' to `\Config\App` structure file

### ISSUE THREAD

**Issue by FaaPz** [devvoh/parable#40]
Yesterday I got stuck on some fatal error what couldn't be shown, because my `parable.debug` option wasn't set. I totally forgot the config option existed, until I dove into Parable's source code.

Adding _all_ of Parable's config options into the `\Config\App` file would be very helpful! 😄

**Comment by FaaPz** [comment]
@devvoh I see you've added `parable.debug` and `parable.timezone` (eadb701752552e257b18894a2588bf0484c111b1). Very nice! 👍 

How about `parable.mail.*`? 😶

**Comment by devvoh** [comment]
That's why I hadn't closed this yet 😉 

I was working on some other changes and needed to make sure it was all under test properly.

Everything I could find is now added. See 942a2c2f1c193eb2d3c856dd5348ba657bdc7eaa for details.
