### ISSUE TITLE
ConsoleApp instantiates and prepares every available command

### ISSUE THREAD

**Issue by dmvdbrugge** [devvoh/parable#47]
It does `init-structure` and `help` itself, and the rest through `CommandLoader`, while only one will be used.

It probably does this to get to know the name of the command to figure out which command must be run, and `help` uses this + description too.

This should be optimised to only instantiate the command to run, and I think name and description should be made static (or use Reflection for non-bc-break \*shivers*).

**Comment by devvoh** [comment]
It definitely does it to get the name + description, and I will fix this in the stand-alone parable-php/console version. Thanks!

**Comment by dmvdbrugge** [comment]
Confusing as it might be, `ConsoleApp` is a `Framework` class, not a `Console` one.

That's why I commented here, and not on `parable-php/console` 😉

**Comment by devvoh** [comment]
... We even talked about that before. I blame the early hour.

Well then, keeping backwards compatibility + performance issue = I'll look into this 😄
