### ISSUE TITLE
extractParameterValues checks for empty(), disabling value '0' 

### ISSUE THREAD

**Issue by jerry1970** [devvoh/parable#48]
In `Route->extractParameterValues`, there is a check for `if (!empty($value))`, which means that the `0` in `/api/users/123/access/0` is skipped. Then there is no route match and a 404 follows.

I think checking for an empty string is enough. `0` or `'0'` should be passed as values as well. Only empty strings are not valid URL parts. The URL is always a string, so NULL will never happen here. I therefore think checking for an empty string is enough to check for in `extractParameterValues`.

**Comment by devvoh** [comment]
Fixed in #49
